cmake_minimum_required(VERSION 3.5)

project(fakechroot)

add_library(${PROJECT_NAME} SHARED
	src/__fxstatat.c
	src/__fxstatat64.c
	src/__getcwd_chk.c
	src/__getwd_chk.c
	src/__lxstat.c
	src/__lxstat64.c
	src/__open.c
	src/__open64.c
	src/__open64_2.c
	src/__open_2.c
	src/__openat64_2.c
	src/__openat_2.c
	src/__opendir2.c
	src/__readlink_chk.c
	src/__readlinkat_chk.c
	src/__realpath_chk.c
	src/__statfs.c
	src/__xmknod.c
	src/__xmknodat.c
	src/__xstat.c
	src/__xstat64.c
	src/_xftw.c
	src/_xftw64.c
	src/access.c
	src/acct.c
	src/audit_log_acct_message.c
	src/bind.c
	src/bindtextdomain.c
	src/canonicalize_file_name.c
	src/chdir.c
	src/chmod.c
	src/chown.c
	src/chroot.c
	src/clearenv.c
	src/connect.c
	src/creat.c
	src/creat64.c
	src/dedotdot.c
	src/dl_iterate_phdr.c
	src/dladdr.c
	src/dlmopen.c
	src/dlopen.c
	src/eaccess.c
	src/euidaccess.c
	src/execl.c
	src/execle.c
	src/execlp.c
	src/execv.c
	src/execve.c
	src/execvp.c
	src/faccessat.c
	src/fchmodat.c
	src/fchownat.c
	src/fopen.c
	src/fopen64.c
	src/freopen.c
	src/freopen64.c
	src/fts.c
	src/fts64.c
	src/ftw.c
	src/ftw64.c
	src/futimesat.c
	src/get_current_dir_name.c
	src/getcwd.c
	src/getcwd_real.c
	src/getpeername.c
	src/getsockname.c
	src/getwd.c
	src/getxattr.c
	src/glob.c
	src/glob64.c
	src/glob_pattern_p.c
	src/inotify_add_watch.c
	src/lchmod.c
	src/lchown.c
	src/lckpwdf.c
	src/lgetxattr.c
	src/libfakechroot.c
	src/link.c
	src/linkat.c
	src/listxattr.c
	src/llistxattr.c
	src/lremovexattr.c
	src/lsetxattr.c
	src/lstat.c
	src/lstat64.c
	src/lutimes.c
	src/mkdir.c
	src/mkdirat.c
	src/mkdtemp.c
	src/mkfifo.c
	src/mkfifoat.c
	src/mknod.c
	src/mknodat.c
	src/mkostemp.c
	src/mkostemp64.c
	src/mkostemps.c
	src/mkostemps64.c
	src/mkstemp.c
	src/mkstemp64.c
	src/mkstemps.c
	src/mkstemps64.c
	src/mktemp.c
	src/open.c
	src/open64.c
	src/openat.c
	src/openat64.c
	src/opendir.c
	src/pathconf.c
	src/popen.c
	src/posix_spawn.c
	src/posix_spawnp.c
	src/rawmemchr.c
	src/readlink.c
	src/readlinkat.c
	src/realpath.c
	src/rel2abs.c
	src/rel2absat.c
	src/remove.c
	src/removexattr.c
	src/rename.c
	src/renameat.c
	src/renameat2.c
	src/revoke.c
	src/rmdir.c
	src/rpl_lstat.c
	src/scandir.c
	src/scandir64.c
	src/setenv.c
	src/setxattr.c
	src/stat.c
	src/stat64.c
	src/statfs.c
	src/statfs64.c
	src/statvfs.c
	src/statvfs64.c
	src/statx.c
	src/stpcpy.c
	src/strchrnul.c
	src/strlcpy.c
	src/symlink.c
	src/symlinkat.c
	src/system.c
	src/tempnam.c
	src/tmpnam.c
	src/truncate.c
	src/truncate64.c
	src/ulckpwdf.c
	src/unlink.c
	src/unlinkat.c
	src/utime.c
	src/utimensat.c
	src/utimes.c)
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_compile_definitions(${PROJECT_NAME} PRIVATE HAVE_CONFIG_H)
target_link_libraries(${PROJECT_NAME} ${CMAKE_DL_LIBS})

